services:

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - pfe-net

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CREATE_TOPICS: "fg_security_events:1:1,fg_traffic_flow:1:1,fg_performance:1:1,fg_device_inventory:1:1,fg_raw_all:1:1"
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - pfe-net

  vector:
    image: timberio/vector:0.36.0-debian
    container_name: vector
    volumes:
      - ./vector.toml:/etc/vector/vector.toml
      - ./data:/data
    command: ["--config", "/etc/vector/vector.toml"]
    ports:
      - "6000:6000"
    depends_on:
      kafka:
        condition: service_healthy
        
    networks:
      - pfe-net

  python_sender:
    image: python:3.12-slim
    container_name: python_sender
    volumes:
      - ./data:/data
      - ./send_csv_to_vector.py:/app/send_csv_to_vector.py
    working_dir: /app
    command: ["python", "send_csv_to_vector.py"]
    networks:
      - pfe-net
    depends_on:
      - vector
    restart: on-failure

  clickhouse:
    image: clickhouse/clickhouse-server:24.3
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_DB: pfe_db
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: admin
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD-SHELL", "clickhouse-client --user admin --password admin --query 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - pfe-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_INSTALL_PLUGINS: grafana-clickhouse-datasource
      GF_SMTP_ENABLED: "true"
      GF_SMTP_HOST: smtp.gmail.com:587
      GF_SMTP_USER: hibapfe01@gmail.com
      GF_SMTP_PASSWORD: rwzzwggknviheoqz
      GF_SMTP_FROM_ADDRESS: hibapfe01@gmail.com
      GF_SMTP_FROM_NAME: Garafana
      GF_SMTP_STARTTLS_POLICY: MandatoryStartTLS
      GF_SMTP_SKIP_VERIFY: "true"

    extra_hosts:
      - "host.docker.internal:host-gateway"

    restart: always
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      clickhouse:
        condition: service_healthy
    networks:
      - pfe-net
      - batch-net

networks:
  pfe-net:
    driver: bridge
  batch-net:
    external: true
    name: test-pfe_batch-net  

volumes:
  grafana-data:
  clickhouse-data:
